services:
  db:
    image: lscr.io/linuxserver/mariadb:11.4.8
    container_name: mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Warsaw
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: filerun-db
      MYSQL_USER: filerun-user
      MYSQL_PASSWORD: filerun-user-password
    volumes:
      - ./db:/config
    restart: unless-stopped

  web:
    build: .
    container_name: filerun_web
    restart: always
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun-db
      FR_DB_USER: filerun-user
      FR_DB_PASS: YOUR_DATABASE_USER_PASSWORD
      PUID: 1000
      PGID: 1000
    depends_on:
      - db
    ports:
      - 5003:80
    volumes:
      - ./user-files:/user-files
      - ./config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge